name = "Promised World Client"
author = "Many Stars Plan Project Teams"
version = "PW-Release-1.0.0-20251024"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7f5726347edfcc6f787524a184a4d2484ab63273a20ea401a19f2cad859de56"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.212"
