name = "Promised World Client"
author = "ManyStars"
version = "1.0.0-beta.1+pw.20251108"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89023894a3994d5e10f133ba36d33a132cdaf222808398147ecbee72cd1db40e"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.213"
