name = "Promised World Client"
author = "Many Stars Plan Project Teams"
version = "PW-Release-1.0.0-20251024"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "494b98109cd2712231e3707fe06a6b5bd085d11348318bfa1f0cf94d2eb41087"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.211"
